# Render Config for ReciePro Backend (Docker)
services:
  - type: web
    name: reciepro-backend
    env: docker
    plan: starter
    rootDir: .
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://receipro.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-ap-southeast-1.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.hncbkbunwokxrmqufylc
      - key: DB_PASSWORD
        sync: false
      - key: APP_KEY
        sync: false
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: supabase
      - key: SUPABASE_ACCESS_KEY_ID
        sync: false
      - key: SUPABASE_SECRET_ACCESS_KEY
        sync: false
      - key: SUPABASE_DEFAULT_REGION
        value: us-east-1
      - key: SUPABASE_BUCKET
        value: receipts
      - key: SUPABASE_ENDPOINT
        sync: false
      - key: SUPABASE_URL
        sync: false
